[telegram]
workers = 1
token = "725730806:AAHi73QEEXhxOaMQFRLqQXbItsILGbzHZ34" # @redditmirrorbot
#token = "285333393:AAEvoP_Q7BdnvGAjgMW5JZoyeuo0jKvV3Cc" # @janembabot
log = -1001141547703
admins = [23646077]

[plugins]
dir = "bot/plugins"
manifest = "manifest"

[jobs]
dir = "bot/jobs"
manifest = "manifest"

[praw]
client_id = "0ri3963pR-qmog"
client_secret = "aM5f4s7KyxaHoI3Y1sUkiSx5tjk"
user_agent = "test script by -"
submissions_limit = 25

[sqlite]
filename = "redditmirror.sqlite"

[logging]
config = "logging.json"
filepath = "logs/redditmirror.log"

[submissions]
default_max_frequency = 115 # minutes (one post every two hours)
default_sorting = "hot"

[quiet_hours]
start = 22 # in UTC. Rome: UTC + 1
end = 7 # in UTC. Rome: UTC + 1

[imgur]
id = "0a9a0e9ec81b35e"
secret = "d866c9c64893558a76d8724b20323522b5757072"
