[telegram]
workers = 1
token = "" #  # CHANGEME
log = -1001141547703 # CHANGEME
admins = [23646077] # CHANGEME
index = "reddit_mirrors" # telegram channel with the channels index
send_images_by_url = true # true: always try to send images by url first, download them only when sendign by url fails
testing = false # subreddit added when this is 'true' will be considered testing subreddits (the bot won't save posted submissions)

[pyrogram]
enabled = true
session_name = "redditbot"
workers = 0
api_id = 12345 # CHANGEME
api_hash = "" # CHANGEME

[[reddit]]
client_id = "" # CHANGEME
client_secret = "" # CHANGEME
user_agent = "" # CHANGEME
username = "" # CHANGEME
password = "" # CHANGEME

[jobs]
posts_cooldown = 1 # how much to sleep when a message is posted, in seconds

[jobs.stream] # in minutes
interval = 10
first = 0

[jobs.resume] # in minutes
interval = 50
first = 0

[sqlite]
filename = "db.sqlite"

[submissions]
default_max_frequency = 115 # minutes (one post every two hours)
default_sorting = "hot"

[imgur]
id = "" # CHANGEME
secret = "" # CHANGEME

[ffmpeg]
cmd_path = "ffmpeg"
cmd_path_windows = "ffmpeg.exe" # needs the .exe binary file in the main project directory

europe_rome_timezone = false
