[telegram]
workers = 1
token = "725730806:AAHi73QEEXhxOaMQFRLqQXbItsILGbzHZ34" # @redditmirrorbot
#token = "285333393:AAEvoP_Q7BdnvGAjgMW5JZoyeuo0jKvV3Cc" # @janembabot
log = -1001141547703
admins = [23646077]
index = "reddit_mirrors" # telegram channel with the channels index

[pyrogram]
session_name = "redditbot"
workers = 0
api_id = 78189
api_hash = "45637520c755297fb626c1926efe1d4f"

[plugins]
dir = "bot/plugins"
manifest = "manifest"

[jobs]
dir = "bot/jobs"
manifest = "manifest"
posts_cooldown = 1 # in seconds

[jobs.posts_job] # in minutes
interval = 10
first = 0

[jobs.resume_job] # in minutes
interval = 50
first = 0

[praw]
client_id = "0ri3963pR-qmog"
client_secret = "aM5f4s7KyxaHoI3Y1sUkiSx5tjk"
user_agent = "test script by -"
submissions_limit = 25

[sqlite]
filename = "db.sqlite"

[logging]
config = "logging.json"
filepath = "logs/redditmirror.log"

[submissions]
default_max_frequency = 115 # minutes (one post every two hours)
default_sorting = "hot"

[quiet_hours]
start = 21 # in UTC. Rome: UTC + 1/2
end = 6 # in UTC. Rome: UTC + 1/2

[imgur]
id = "0a9a0e9ec81b35e"
secret = "d866c9c64893558a76d8724b20323522b5757072"

[ffmpeg]
cmd_path = "ffmpeg"
cmd_path_windows = "ffmpeg.exe" # needs the .exe binary file in the main project directory
