[telegram]
workers = 1
token = "725730806:AAHi73QEEXhxOaMQFRLqQXbItsILGbzHZ34" # @redditmirrorbot
admins = [23646077]

[plugins]
dir = "bot/plugins"
manifest = "manifest"

[jobs]
dir = "bot/jobs"
manifest = "manifest"

[praw]
client_id = "0ri3963pR-qmog"
client_secret = "aM5f4s7KyxaHoI3Y1sUkiSx5tjk"
user_agent = "test script by -"
submissions_limit = 25

[sqlite]
filename = "redditmirror.sqlite"

[logging]
config = "logging.json"
filepath = "logs/redditmirror.log"

[submissions]
default_max_frequency = 33 # minutes
default_sorting = "hot"

[quiet_hours]
enabled = true
start = 23
end = 9
timezone = ""
