[telegram]
workers = 1
token = "" #  # CHANGEME
log = -1001141547703 # CHANGEME
admins = [23646077] # CHANGEME
index = "reddit_mirrors" # telegram channel with the channels index
send_images_by_url = true # true: always try to send images by url first, download them only when sendign by url fails
testing = false # subreddit added when this is 'true' will be considered testing subreddits (the bot won't save posted submissions)

[pyrogram]
enabled = true
session_name = "redditbot"
workers = 0
api_id = 12345 # CHANGEME
api_hash = "" # CHANGEME

[jobs]
posts_cooldown = 1 # how much to sleep when a message is posted, in seconds

[jobs.stream] # in minutes
interval = 10
first = 0.5 # 0: "interval" will be used instead

[sqlite]
filename = "db.sqlite"

[imgur]
# get your secret keys from here: https://api.imgur.com/oauth2/addclient
# more info: https://github.com/faustocarrera/imgur-python/wiki
id = "" # CHANGEME
secret = "" # CHANGEME

[ffmpeg]
cmd_path = "ffmpeg"
cmd_path_windows = "ffmpeg.exe" # needs the .exe binary file in the main project directory

europe_rome_timezone = false
