[telegram]
token = ""
admins = []

[praw]
client_id = "0ri3963pR-qmog"
client_secret = "aM5f4s7KyxaHoI3Y1sUkiSx5tjk"
user_agent = "test script by -"
submissions_limit = 25

[sqlite]
filename = "redditmirror.sqlite"

[logging]
config = "logging.json"
path = "logs/redditmirror.log"

[submissions]
default_max_frequency = 25 # minutes
default_sorting = "hot"

[quite_hours]
enabled = true
start = 23
end = 9
timezone = ""
