[general]
prefer_least_used_account = false # to execute requests, prefere the least used account instead of the default one
stress_threshold_hours = 48 # when calculating the least used account, consider the requests sent in the past n hours

[[accounts]]
default = true
username = ""
password = ""

[[accounts.clients]]
default = true
name = "unique-name-1"
client_id = ""
client_secret = ""
user_agent = ""

[[accounts.clients]]
name = "unique-name-1"
client_id = ""
client_secret = ""
user_agent = ""



[[accounts]]
username = "username"
password = ""

[[accounts.clients]]
name = "unique-name-1"
default = true
client_id = ""
client_secret = ""
user_agent = ""
