[[reddit.accounts]]
default = true
username = "example_account_1"
password = ""

[[reddit.accounts]]
username = "example_account_2"
password = ""



[[reddit.clients]]
default = true
name = "example-client-1"
client_id = ""
client_secret = ""
user_agent = "test script by -"

[[reddit.clients]]
name = "example-client-2"
client_id = ""
client_secret = ""
user_agent = "test script by -"