class Status:
    SUBREDDIT_SELECT = 10
    CHANNEL_SELECT = 20
    WAITING_ORIGIN_SUBREDDIT = 30
    WAITING_FORWARDED_MESSAGE = 40
    WAITING_SUBREDDIT_CONFIG_ACTION = 50
    CLONE_WAITING_ORIGIN_SUBREDDIT = 60
    CLONESTYLE_WAITING_ORIGIN_SUBREDDIT = 70
    SETCHANNEL_WAITING_CHANNEL = 80
    STYLE_SELECT = 90
    WAITING_STYLE_CONFIG_ACTION = 100
    SUBREDDIT_WAITING_STYLE = 110
    END = -1
    TIMEOUT = -2
    NONE_RETURNED = -10  # this is for handlers that are not part of a conversation, so they return None


STATUSES_DICT = {
    Status.END: 'conversation ended',
    Status.TIMEOUT: 'conversation timed out',
    Status.SUBREDDIT_SELECT: 'SUBREDDIT_SELECT',
    Status.CHANNEL_SELECT: 'CHANNEL_SELECT',
    Status.WAITING_ORIGIN_SUBREDDIT: 'WAITING_ORIGIN_SUBREDDIT',
    Status.WAITING_FORWARDED_MESSAGE: 'WAITING_FORWARDED_MESSAGE',
    Status.WAITING_SUBREDDIT_CONFIG_ACTION: 'WAITING_SUBREDDIT_CONFIG_ACTION',
    Status.CLONE_WAITING_ORIGIN_SUBREDDIT: 'CLONE_WAITING_ORIGIN_SUBREDDIT',
    Status.CLONESTYLE_WAITING_ORIGIN_SUBREDDIT: 'CLONESTYLE_WAITING_ORIGIN_SUBREDDIT',
    Status.SETCHANNEL_WAITING_CHANNEL: 'SETCHANNEL_WAITING_CHANNEL',
    Status.STYLE_SELECT: 'STYLE_SELECT',
    Status.WAITING_STYLE_CONFIG_ACTION: 'WAITING_STYLE_CONFIG_ACTION',
    Status.SUBREDDIT_WAITING_STYLE: 'SUBREDDIT_WAITING_STYLE',
    Status.NONE_RETURNED: 'no next status returned'
}


def get_status_description(status_value):
    return STATUSES_DICT.get(status_value, 'unmapped value')
